-- ==============================================================================
-- FULL SCHEMA SNAPSHOT v1 (2026-01-12)
-- This file represents the stable state of the database including all fixes.
-- Use this to restore the database structure if needed.
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. TABLE UPDATES & MISSING COLUMNS
-- ------------------------------------------------------------------------------

-- Settings Table (The most critical one)
CREATE TABLE IF NOT EXISTS public.settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    restaurant_id uuid REFERENCES public.restaurants(id) ON DELETE CASCADE,
    
    -- Branding
    theme_color text DEFAULT 'black',
    font_family text DEFAULT 'Inter',
    dark_mode boolean DEFAULT false,
    logo_url text,
    logo_width integer DEFAULT 150,
    site_name text,
    site_description text,
    
    -- Banner System
    banner_active boolean DEFAULT false,
    banner_urls text[] DEFAULT ARRAY[]::text[],
    mobile_banner_urls text[] DEFAULT ARRAY[]::text[],
    banner_overlay_visible boolean DEFAULT true,
    banner_tag text DEFAULT 'FIRSAT',
    banner_title text DEFAULT 'Kampanya',
    banner_subtitle text DEFAULT '%20 İndirim',
    
    -- Popup
    popup_active boolean DEFAULT false,
    popup_url text,
    
    -- Category Styling
    category_font_size text DEFAULT 'large',
    category_font_weight text DEFAULT 'black',
    category_row_height text DEFAULT 'medium',
    category_gap text DEFAULT 'medium',
    category_overlay_opacity integer DEFAULT 50,
    category_font_family text DEFAULT 'Inter',
    category_letter_spacing text DEFAULT 'normal',
    category_char_convert boolean DEFAULT false,
    
    -- Product Styling
    product_title_color text DEFAULT '#111827',
    product_description_color text DEFAULT '#6b7280',
    product_price_color text DEFAULT '#d97706',
    product_title_size text DEFAULT 'large',
    product_description_size text DEFAULT 'medium',
    product_price_size text DEFAULT 'large',
    
    -- Default Images
    default_product_image text,
    
    -- Social
    social_instagram text,
    social_whatsapp text,
    social_google_maps text,
    social_wifi_password text,
    
    CONSTRAINT settings_restaurant_id_key UNIQUE (restaurant_id)
);

-- Products Table Updates
ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS tags jsonb DEFAULT '[]',
ADD COLUMN IF NOT EXISTS allergens jsonb DEFAULT '[]',
ADD COLUMN IF NOT EXISTS badge text,
ADD COLUMN IF NOT EXISTS variants jsonb DEFAULT '[]',
ADD COLUMN IF NOT EXISTS discount_price numeric;

-- Categories Table Updates
ALTER TABLE public.categories
ADD COLUMN IF NOT EXISTS layout_mode text DEFAULT 'grid';

-- ------------------------------------------------------------------------------
-- 2. PERFORMANCE INDEXES
-- ------------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_products_restaurant_id ON public.products(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_products_category_id ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_categories_restaurant_id ON public.categories(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_orders_restaurant_id ON public.orders(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_settings_restaurant_id ON public.settings(restaurant_id);

-- ------------------------------------------------------------------------------
-- 3. SAFETY CHECKS & DATA FIXES
-- ------------------------------------------------------------------------------

-- Ensure array types are correct and not null
UPDATE public.settings SET banner_urls = '{}' WHERE banner_urls IS NULL;
UPDATE public.settings SET mobile_banner_urls = '{}' WHERE mobile_banner_urls IS NULL;

-- ------------------------------------------------------------------------------
-- 4. RELOAD SCHEMA CACHE
-- ------------------------------------------------------------------------------
NOTIFY pgrst, 'reload schema';
